// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taxi.Api.Infrastructure;

#nullable disable

namespace Taxi.Api.Infrastructure.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<JsonDocument>("Diff")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_audit_logs_fleet_id");

                    b.HasIndex("FleetId", "At")
                        .HasDatabaseName("ix_audit_logs_fleet_id_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_vehicle_id");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("LastLat")
                        .HasColumnType("double precision")
                        .HasColumnName("last_lat");

                    b.Property<double?>("LastLng")
                        .HasColumnType("double precision")
                        .HasColumnName("last_lng");

                    b.Property<DateTimeOffset?>("LastPositionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_position_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.HasIndex("CurrentVehicleId")
                        .HasDatabaseName("ix_drivers_current_vehicle_id");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_drivers_fleet_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_user_id");

                    b.HasIndex("FleetId", "Status")
                        .HasDatabaseName("ix_drivers_fleet_id_status");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.DriverShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_shifts");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_shifts_driver_id");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_driver_shifts_fleet_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_driver_shifts_vehicle_id");

                    b.ToTable("driver_shifts", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LogoUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logo_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color_hex");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_fleets");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_fleets_slug");

                    b.ToTable("fleets", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.FleetSettings", b =>
                {
                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<int>("AutoDispatchAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("auto_dispatch_after_seconds");

                    b.Property<bool>("AutoDispatchEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_dispatch_enabled");

                    b.Property<int>("MaxOfferRadiusKm")
                        .HasColumnType("integer")
                        .HasColumnName("max_offer_radius_km");

                    b.Property<int>("OfferTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("offer_timeout_seconds");

                    b.Property<int>("SmsMonthlyCapCzk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("sms_monthly_cap_czk");

                    b.Property<string>("SmsSenderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sms_sender_name");

                    b.Property<int>("SmsUnitCostCzk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sms_unit_cost_czk");

                    b.Property<string>("WelcomeText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("welcome_text");

                    b.HasKey("FleetId")
                        .HasName("pk_fleet_settings");

                    b.ToTable("fleet_settings", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<JsonDocument>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_records_created_at");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_user_id_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notification_log");

                    b.HasIndex("FleetId", "OrderId")
                        .HasDatabaseName("ix_notification_log_fleet_id_order_id");

                    b.HasIndex("FleetId", "Event", "OrderId", "Recipient", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_log_fleet_id_event_order_id_recipient_channel");

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.NotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<JsonDocument>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecipientEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recipient_endpoint");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_phone");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_notification_outbox_fleet_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_outbox_status_next_attempt_at");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledByRole")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by_role");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dropoff_address");

                    b.Property<double?>("DropoffLat")
                        .HasColumnType("double precision")
                        .HasColumnName("dropoff_lat");

                    b.Property<double?>("DropoffLng")
                        .HasColumnType("double precision")
                        .HasColumnName("dropoff_lng");

                    b.Property<int?>("EstimatedPriceCzk")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_price_czk");

                    b.Property<int?>("FinalPriceCzk")
                        .HasColumnType("integer")
                        .HasColumnName("final_price_czk");

                    b.Property<int?>("FixedPriceCzk")
                        .HasColumnType("integer")
                        .HasColumnName("fixed_price_czk");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_address");

                    b.Property<double>("PickupLat")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_lat");

                    b.Property<double>("PickupLng")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_lng");

                    b.Property<string>("PriceOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("price_override_reason");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_type");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("public_code");

                    b.Property<DateTimeOffset?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<string>("RatingComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rating_comment");

                    b.Property<int?>("RatingStars")
                        .HasColumnType("integer")
                        .HasColumnName("rating_stars");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_orders_created_by_user_id");

                    b.HasIndex("CustomerUserId")
                        .HasDatabaseName("ix_orders_customer_user_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_orders_driver_id");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_orders_fleet_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_orders_route_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_orders_vehicle_id");

                    b.HasIndex("FleetId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_orders_fleet_id_created_at");

                    b.HasIndex("FleetId", "PublicCode")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_fleet_id_public_code");

                    b.HasIndex("FleetId", "ScheduledAt")
                        .HasDatabaseName("ix_orders_fleet_id_scheduled_at");

                    b.HasIndex("FleetId", "Status")
                        .HasDatabaseName("ix_orders_fleet_id_status");

                    b.HasIndex("FleetId", "DriverId", "CreatedAt")
                        .HasDatabaseName("ix_orders_fleet_id_driver_id_created_at");

                    b.HasIndex("FleetId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_fleet_id_status_created_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_order_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_order_events_actor_user_id");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_order_events_fleet_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_events_order_id");

                    b.HasIndex("FleetId", "At")
                        .HasDatabaseName("ix_order_events_fleet_id_at");

                    b.HasIndex("OrderId", "At")
                        .HasDatabaseName("ix_order_events_order_id_at");

                    b.ToTable("order_events", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_places_fleet_id");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<Guid?>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_push_subscriptions_fleet_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<double>("FromLat")
                        .HasColumnType("double precision")
                        .HasColumnName("from_lat");

                    b.Property<double>("FromLng")
                        .HasColumnType("double precision")
                        .HasColumnName("from_lng");

                    b.Property<double>("FromRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(150.0)
                        .HasColumnName("from_radius_meters");

                    b.Property<Guid?>("FromZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_zone_id");

                    b.Property<bool>("IsBidirectional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_bidirectional");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PriceCzk")
                        .HasColumnType("integer")
                        .HasColumnName("price_czk");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<double?>("ToLat")
                        .HasColumnType("double precision")
                        .HasColumnName("to_lat");

                    b.Property<double?>("ToLng")
                        .HasColumnType("double precision")
                        .HasColumnName("to_lng");

                    b.Property<double>("ToRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(150.0)
                        .HasColumnName("to_radius_meters");

                    b.Property<Guid?>("ToZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_zone_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("ValidDays")
                        .HasColumnType("integer")
                        .HasColumnName("valid_days");

                    b.Property<TimeOnly?>("ValidFromTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("valid_from_time");

                    b.Property<TimeOnly?>("ValidToTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("valid_to_time");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_routes_fleet_id");

                    b.HasIndex("FromZoneId")
                        .HasDatabaseName("ix_routes_from_zone_id");

                    b.HasIndex("ToZoneId")
                        .HasDatabaseName("ix_routes_to_zone_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.SmsCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_sms_codes");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_sms_codes_phone");

                    b.ToTable("sms_codes", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseFareCzk")
                        .HasColumnType("integer")
                        .HasColumnName("base_fare_czk");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MinimumFareCzk")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_fare_czk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PerKmCzk")
                        .HasColumnType("integer")
                        .HasColumnName("per_km_czk");

                    b.Property<int>("PerMinuteWaitingCzk")
                        .HasColumnType("integer")
                        .HasColumnName("per_minute_waiting_czk");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_tariffs_fleet_id");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_users_fleet_id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone")
                        .HasFilter("role = 'Customer'");

                    b.HasIndex("FleetId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_fleet_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plate");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_vehicles_fleet_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lat");

                    b.Property<double>("CenterLng")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lng");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("Polygon")
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("FleetId")
                        .HasDatabaseName("ix_zones_fleet_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.AuditLog", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Driver", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("CurrentVehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_drivers_vehicles_current_vehicle_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_users_user_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.DriverShift", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driver_shifts_drivers_driver_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driver_shifts_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driver_shifts_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.FleetSettings", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fleet_settings_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_users_user_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.NotificationLog", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_log_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.NotificationOutbox", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_outbox_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Order", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_created_by_user_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_customer_user_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_drivers_driver_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_routes_route_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.OrderEvent", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_events_users_actor_user_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_events_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_events_orders_order_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Place", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.PushSubscription", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_push_subscriptions_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Route", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_fleets_fleet_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("FromZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_routes_zones_from_zone_id");

                    b.HasOne("Taxi.Api.Infrastructure.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("ToZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_routes_zones_to_zone_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Tariff", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tariffs_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Vehicle", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_fleets_fleet_id");
                });

            modelBuilder.Entity("Taxi.Api.Infrastructure.Entities.Zone", b =>
                {
                    b.HasOne("Taxi.Api.Infrastructure.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zones_fleets_fleet_id");
                });
#pragma warning restore 612, 618
        }
    }
}
