import type { DefaultTheme } from 'styled-components'

export const theme: DefaultTheme = {
  colors: {
    primary: '#1a73e8',
    primaryDark: '#1558b0',
    background: '#f8f9fa',
    surface: '#ffffff',
    border: '#dadce0',
    text: '#202124',
    textSecondary: '#5f6368',
    error: '#d93025',
    warning: '#f9ab00',
    success: '#188038',
    // Status pill palette
    statusFree: '#188038',
    statusFreeText: '#ffffff',
    statusBusy: '#f9ab00',
    statusBusyText: '#202124',
    statusEnRoute: '#1a73e8',
    statusEnRouteText: '#ffffff',
    statusOffline: '#5f6368',
    statusOfflineText: '#ffffff',
    // Order status pills
    orderNew: '#1a73e8',
    orderNewText: '#ffffff',
    orderAssigned: '#f9ab00',
    orderAssignedText: '#202124',
    orderInProgress: '#188038',
    orderInProgressText: '#ffffff',
    orderCompleted: '#5f6368',
    orderCompletedText: '#ffffff',
    orderCancelled: '#d93025',
    orderCancelledText: '#ffffff',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  typography: {
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
    fontSizeXs: '11px',
    fontSizeSm: '13px',
    fontSizeMd: '15px',
    fontSizeLg: '18px',
    fontSizeXl: '22px',
    fontWeightNormal: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    lineHeight: 1.5,
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 3px rgba(0,0,0,0.12)',
    md: '0 2px 8px rgba(0,0,0,0.15)',
    lg: '0 4px 16px rgba(0,0,0,0.20)',
  },
  breakpoints: {
    desktop: '1280px',
    wide: '1600px',
  },
}
